### PR TITLE
Fixed retries not happening in waitForTable

### PR DESCRIPTION
**Pull request by moejay**

### CODE REVIEW

**Comment by austinkelleher** [comment]
Thanks and good catch! Published `dynograte@2.2.1` with this fix.

**Comment by moejay** [comment]
Thanks for the quick merge.
Nice library!

**Comment by austinkelleher** [comment]
@moejay Thanks! I'm not actively maintaining this library anymore. Are you using it? Would you be interested in helping maintain it?

**Comment by moejay** [comment]
Unfortunately, I don't think I can commit the time, but happy to help when I can

**Pull request merged**
